spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/Sector
    username: sa
    password:
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  # H2 properties
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
  security:
    user:
      name: user
      password: pass
app:
  cors:
    allowed-origins: http://localhost:3000







